-- OpsPilot initial schema for MySQL 8.0.39.
-- Design goals: long-term extensibility, auditable task execution, Agent-first operations,
-- and clear separation between definitions, runs, attempts, logs, alerts, webhooks and audit data.

SET NAMES utf8mb4;
SET time_zone = '+08:00';

CREATE TABLE IF NOT EXISTS workspaces (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL COMMENT 'ULID exposed to API clients',
  name VARCHAR(128) NOT NULL,
  slug VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_workspaces_uid (uid),
  UNIQUE KEY uk_workspaces_slug (slug),
  KEY idx_workspaces_status (status),
  CONSTRAINT chk_workspaces_status CHECK (status IN ('active', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL COMMENT 'ULID exposed to API clients',
  username VARCHAR(64) NOT NULL,
  email VARCHAR(191) NULL,
  phone VARCHAR(32) NULL,
  display_name VARCHAR(128) NULL,
  password_hash VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(512) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  last_login_at DATETIME(3) NULL,
  password_changed_at DATETIME(3) NULL,
  mfa_enabled TINYINT(1) NOT NULL DEFAULT 0,
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_uid (uid),
  UNIQUE KEY uk_users_username (username),
  UNIQUE KEY uk_users_email (email),
  KEY idx_users_status (status),
  CONSTRAINT chk_users_status CHECK (status IN ('active', 'disabled', 'locked', 'deleted'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS workspace_members (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  member_type VARCHAR(32) NOT NULL DEFAULT 'human',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  joined_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_workspace_members_user (workspace_id, user_id),
  KEY idx_workspace_members_user (user_id),
  KEY idx_workspace_members_status (workspace_id, status),
  CONSTRAINT fk_workspace_members_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_workspace_members_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT chk_workspace_members_type CHECK (member_type IN ('human', 'service_account')),
  CONSTRAINT chk_workspace_members_status CHECK (status IN ('active', 'invited', 'disabled', 'removed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS permissions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(128) NOT NULL COMMENT 'Example: task.run, agent.disable',
  module VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(512) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_permissions_code (code),
  KEY idx_permissions_module (module)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NULL COMMENT 'NULL means system role template',
  code VARCHAR(96) NOT NULL,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(512) NULL,
  built_in TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_roles_uid (uid),
  UNIQUE KEY uk_roles_scope_code ((IFNULL(workspace_id, 0)), code),
  KEY idx_roles_workspace_status (workspace_id, status),
  KEY idx_roles_created_by (created_by),
  CONSTRAINT fk_roles_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_roles_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_roles_status CHECK (status IN ('active', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id BIGINT UNSIGNED NOT NULL,
  permission_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (role_id, permission_id),
  KEY idx_role_permissions_permission (permission_id),
  CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  role_id BIGINT UNSIGNED NOT NULL,
  granted_by BIGINT UNSIGNED NULL,
  expires_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_roles_scope (workspace_id, user_id, role_id),
  KEY idx_user_roles_user (user_id),
  KEY idx_user_roles_role (role_id),
  KEY idx_user_roles_granted_by (granted_by),
  CONSTRAINT fk_user_roles_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_roles_granted_by FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL,
  token_family CHAR(36) NOT NULL,
  user_agent VARCHAR(512) NULL,
  ip VARCHAR(45) NULL,
  expires_at DATETIME(3) NOT NULL,
  revoked_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_refresh_tokens_hash (token_hash),
  KEY idx_refresh_tokens_user (user_id, expires_at),
  KEY idx_refresh_tokens_family (token_family),
  CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS login_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  username VARCHAR(128) NULL,
  result VARCHAR(32) NOT NULL,
  reason VARCHAR(255) NULL,
  ip VARCHAR(45) NULL,
  user_agent VARCHAR(512) NULL,
  trace_id VARCHAR(64) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_login_logs_user_created (user_id, created_at),
  KEY idx_login_logs_result_created (result, created_at),
  CONSTRAINT fk_login_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_login_logs_result CHECK (result IN ('success', 'failed', 'locked', 'blocked'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS system_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NULL,
  setting_key VARCHAR(128) NOT NULL,
  setting_value JSON NULL,
  value_type VARCHAR(32) NOT NULL DEFAULT 'json',
  encrypted TINYINT(1) NOT NULL DEFAULT 0,
  description VARCHAR(512) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_system_settings_scope_key ((IFNULL(workspace_id, 0)), setting_key),
  KEY idx_system_settings_workspace (workspace_id),
  CONSTRAINT fk_system_settings_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(64) NOT NULL,
  color VARCHAR(32) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_tags_workspace_name (workspace_id, name),
  CONSTRAINT fk_tags_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS resource_tags (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL,
  tag_id BIGINT UNSIGNED NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_resource_tags_unique (workspace_id, tag_id, resource_type, resource_id),
  KEY idx_resource_tags_resource (workspace_id, resource_type, resource_id),
  CONSTRAINT fk_resource_tags_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_resource_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS host_groups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(512) NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_host_groups_uid (uid),
  UNIQUE KEY uk_host_groups_workspace_name (workspace_id, name),
  KEY idx_host_groups_created_by (created_by),
  CONSTRAINT fk_host_groups_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_host_groups_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS hosts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  hostname VARCHAR(255) NULL,
  primary_ip VARCHAR(45) NULL,
  os_type VARCHAR(64) NULL,
  os_name VARCHAR(128) NULL,
  os_version VARCHAR(128) NULL,
  arch VARCHAR(64) NULL,
  cpu_cores INT UNSIGNED NULL,
  memory_bytes BIGINT UNSIGNED NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'unknown',
  metadata JSON NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_hosts_uid (uid),
  UNIQUE KEY uk_hosts_workspace_name (workspace_id, name),
  KEY idx_hosts_workspace_status (workspace_id, status),
  KEY idx_hosts_primary_ip (primary_ip),
  KEY idx_hosts_created_by (created_by),
  CONSTRAINT fk_hosts_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_hosts_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_hosts_status CHECK (status IN ('unknown', 'online', 'offline', 'disabled', 'maintenance'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS host_group_members (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  host_group_id BIGINT UNSIGNED NOT NULL,
  host_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_host_group_members_unique (host_group_id, host_id),
  KEY idx_host_group_members_host (host_id),
  CONSTRAINT fk_host_group_members_group FOREIGN KEY (host_group_id) REFERENCES host_groups(id) ON DELETE CASCADE,
  CONSTRAINT fk_host_group_members_host FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS agents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  host_id BIGINT UNSIGNED NULL,
  name VARCHAR(128) NOT NULL,
  token_hash CHAR(64) NOT NULL,
  token_prefix VARCHAR(16) NULL,
  version VARCHAR(64) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'registered',
  os_type VARCHAR(64) NULL,
  arch VARCHAR(64) NULL,
  ip VARCHAR(45) NULL,
  last_heartbeat_at DATETIME(3) NULL,
  disabled_at DATETIME(3) NULL,
  disabled_by BIGINT UNSIGNED NULL,
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_agents_uid (uid),
  UNIQUE KEY uk_agents_token_hash (token_hash),
  UNIQUE KEY uk_agents_workspace_name (workspace_id, name),
  KEY idx_agents_workspace_status_heartbeat (workspace_id, status, last_heartbeat_at),
  KEY idx_agents_host (host_id),
  KEY idx_agents_disabled_by (disabled_by),
  CONSTRAINT fk_agents_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_agents_host FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE SET NULL,
  CONSTRAINT fk_agents_disabled_by FOREIGN KEY (disabled_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_agents_status CHECK (status IN ('registered', 'online', 'offline', 'disabled', 'upgrading'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS agent_tokens (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  agent_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL,
  token_prefix VARCHAR(16) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  last_used_at DATETIME(3) NULL,
  expires_at DATETIME(3) NULL,
  rotated_at DATETIME(3) NULL,
  revoked_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_tokens_hash (token_hash),
  KEY idx_agent_tokens_agent_status (agent_id, status),
  CONSTRAINT fk_agent_tokens_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT chk_agent_tokens_status CHECK (status IN ('active', 'rotated', 'revoked', 'expired'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS agent_heartbeats (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  agent_id BIGINT UNSIGNED NOT NULL,
  host_id BIGINT UNSIGNED NULL,
  status VARCHAR(32) NOT NULL,
  ip VARCHAR(45) NULL,
  version VARCHAR(64) NULL,
  payload JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_agent_heartbeats_agent_created (agent_id, created_at),
  KEY idx_agent_heartbeats_host_created (host_id, created_at),
  CONSTRAINT fk_agent_heartbeats_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_heartbeats_host FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS agent_commands (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  agent_id BIGINT UNSIGNED NOT NULL,
  command_type VARCHAR(64) NOT NULL,
  payload JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  error_message VARCHAR(1024) NULL,
  created_by BIGINT UNSIGNED NULL,
  claimed_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_commands_uid (uid),
  KEY idx_agent_commands_agent_status (agent_id, status, created_at),
  KEY idx_agent_commands_created_by (created_by),
  CONSTRAINT fk_agent_commands_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_commands_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_agent_commands_status CHECK (status IN ('pending', 'claimed', 'success', 'failed', 'expired', 'canceled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS script_templates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(1024) NULL,
  script_type VARCHAR(32) NOT NULL DEFAULT 'shell',
  risk_level VARCHAR(32) NOT NULL DEFAULT 'medium',
  approval_required TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_script_templates_uid (uid),
  UNIQUE KEY uk_script_templates_workspace_name (workspace_id, name),
  KEY idx_script_templates_workspace_status (workspace_id, status),
  KEY idx_script_templates_created_by (created_by),
  CONSTRAINT fk_script_templates_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_script_templates_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_script_templates_type CHECK (script_type IN ('shell', 'powershell', 'python', 'custom')),
  CONSTRAINT chk_script_templates_risk CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
  CONSTRAINT chk_script_templates_status CHECK (status IN ('draft', 'active', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS script_versions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  template_id BIGINT UNSIGNED NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  title VARCHAR(128) NULL,
  content MEDIUMTEXT NOT NULL,
  variables_schema JSON NULL,
  checksum CHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  change_summary VARCHAR(1024) NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_script_versions_uid (uid),
  UNIQUE KEY uk_script_versions_template_version (template_id, version_no),
  UNIQUE KEY uk_script_versions_template_checksum (template_id, checksum),
  KEY idx_script_versions_template_status (template_id, status),
  KEY idx_script_versions_created_by (created_by),
  CONSTRAINT fk_script_versions_template FOREIGN KEY (template_id) REFERENCES script_templates(id) ON DELETE CASCADE,
  CONSTRAINT fk_script_versions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_script_versions_status CHECK (status IN ('draft', 'active', 'deprecated', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS script_approvals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  script_version_id BIGINT UNSIGNED NOT NULL,
  approver_id BIGINT UNSIGNED NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  comment VARCHAR(1024) NULL,
  approved_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_script_approvals_version_status (script_version_id, status),
  KEY idx_script_approvals_approver (approver_id),
  CONSTRAINT fk_script_approvals_version FOREIGN KEY (script_version_id) REFERENCES script_versions(id) ON DELETE CASCADE,
  CONSTRAINT fk_script_approvals_approver FOREIGN KEY (approver_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_script_approvals_status CHECK (status IN ('pending', 'approved', 'rejected', 'canceled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(1024) NULL,
  script_template_id BIGINT UNSIGNED NOT NULL,
  script_version_id BIGINT UNSIGNED NOT NULL,
  default_parameters JSON NULL,
  timeout_seconds INT UNSIGNED NOT NULL,
  max_parallel INT UNSIGNED NOT NULL DEFAULT 1,
  retry_policy JSON NULL,
  trigger_mode VARCHAR(32) NOT NULL DEFAULT 'manual',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_tasks_uid (uid),
  UNIQUE KEY uk_tasks_workspace_name (workspace_id, name),
  KEY idx_tasks_workspace_status (workspace_id, status),
  KEY idx_tasks_script_template (script_template_id),
  KEY idx_tasks_script_version (script_version_id),
  KEY idx_tasks_created_by (created_by),
  CONSTRAINT fk_tasks_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_tasks_script_template FOREIGN KEY (script_template_id) REFERENCES script_templates(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tasks_script_version FOREIGN KEY (script_version_id) REFERENCES script_versions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tasks_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_tasks_timeout CHECK (timeout_seconds > 0),
  CONSTRAINT chk_tasks_trigger CHECK (trigger_mode IN ('manual', 'schedule', 'webhook', 'api')),
  CONSTRAINT chk_tasks_status CHECK (status IN ('active', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS task_targets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  agent_id BIGINT UNSIGNED NULL,
  host_id BIGINT UNSIGNED NULL,
  host_group_id BIGINT UNSIGNED NULL,
  selector JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_task_targets_task (task_id),
  KEY idx_task_targets_agent (agent_id),
  KEY idx_task_targets_host (host_id),
  KEY idx_task_targets_group (host_group_id),
  CONSTRAINT fk_task_targets_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_targets_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE SET NULL,
  CONSTRAINT fk_task_targets_host FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE SET NULL,
  CONSTRAINT fk_task_targets_group FOREIGN KEY (host_group_id) REFERENCES host_groups(id) ON DELETE SET NULL,
  CONSTRAINT chk_task_targets_type CHECK (target_type IN ('agent', 'host', 'host_group', 'dynamic_query'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS task_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  task_id BIGINT UNSIGNED NOT NULL,
  script_version_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  trigger_type VARCHAR(32) NOT NULL DEFAULT 'manual',
  trigger_id BIGINT UNSIGNED NULL,
  idempotency_key VARCHAR(128) NULL,
  parameters JSON NULL,
  timeout_seconds INT UNSIGNED NOT NULL,
  total_targets INT UNSIGNED NOT NULL DEFAULT 0,
  success_targets INT UNSIGNED NOT NULL DEFAULT 0,
  failed_targets INT UNSIGNED NOT NULL DEFAULT 0,
  canceled_targets INT UNSIGNED NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  cancel_requested_by BIGINT UNSIGNED NULL,
  cancel_reason VARCHAR(512) NULL,
  queued_at DATETIME(3) NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  duration_ms BIGINT UNSIGNED NULL,
  error_message VARCHAR(2048) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_runs_uid (uid),
  UNIQUE KEY uk_task_runs_idempotency (workspace_id, idempotency_key),
  KEY idx_task_runs_workspace_status_created (workspace_id, status, created_at),
  KEY idx_task_runs_task_created (task_id, created_at),
  KEY idx_task_runs_created_by (created_by),
  KEY idx_task_runs_cancel_requested_by (cancel_requested_by),
  CONSTRAINT fk_task_runs_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_runs_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE RESTRICT,
  CONSTRAINT fk_task_runs_script_version FOREIGN KEY (script_version_id) REFERENCES script_versions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_task_runs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_task_runs_cancel_by FOREIGN KEY (cancel_requested_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_task_runs_status CHECK (status IN ('pending', 'queued', 'dispatched', 'running', 'canceling', 'success', 'failed', 'timeout', 'canceled')),
  CONSTRAINT chk_task_runs_trigger CHECK (trigger_type IN ('manual', 'schedule', 'webhook', 'api', 'retry'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS task_run_targets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  run_id BIGINT UNSIGNED NOT NULL,
  task_target_id BIGINT UNSIGNED NULL,
  agent_id BIGINT UNSIGNED NULL,
  host_id BIGINT UNSIGNED NULL,
  target_snapshot JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  current_attempt_no INT UNSIGNED NOT NULL DEFAULT 0,
  exit_code INT NULL,
  error_message VARCHAR(2048) NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  duration_ms BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_run_targets_uid (uid),
  KEY idx_task_run_targets_run_status (run_id, status),
  KEY idx_task_run_targets_agent_status (agent_id, status),
  KEY idx_task_run_targets_host (host_id),
  KEY idx_task_run_targets_task_target (task_target_id),
  CONSTRAINT fk_task_run_targets_run FOREIGN KEY (run_id) REFERENCES task_runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_run_targets_task_target FOREIGN KEY (task_target_id) REFERENCES task_targets(id) ON DELETE SET NULL,
  CONSTRAINT fk_task_run_targets_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE SET NULL,
  CONSTRAINT fk_task_run_targets_host FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE SET NULL,
  CONSTRAINT chk_task_run_targets_status CHECK (status IN ('pending', 'queued', 'dispatched', 'running', 'canceling', 'success', 'failed', 'timeout', 'canceled', 'skipped'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS task_run_attempts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  run_id BIGINT UNSIGNED NOT NULL,
  run_target_id BIGINT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NULL,
  attempt_no INT UNSIGNED NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  command_id BIGINT UNSIGNED NULL,
  process_id VARCHAR(64) NULL,
  exit_code INT NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  duration_ms BIGINT UNSIGNED NULL,
  error_message VARCHAR(2048) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_run_attempts_uid (uid),
  UNIQUE KEY uk_task_run_attempts_no (run_target_id, attempt_no),
  KEY idx_task_run_attempts_run_status (run_id, status),
  KEY idx_task_run_attempts_agent (agent_id),
  KEY idx_task_run_attempts_command (command_id),
  CONSTRAINT fk_task_run_attempts_run FOREIGN KEY (run_id) REFERENCES task_runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_run_attempts_target FOREIGN KEY (run_target_id) REFERENCES task_run_targets(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_run_attempts_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE SET NULL,
  CONSTRAINT fk_task_run_attempts_command FOREIGN KEY (command_id) REFERENCES agent_commands(id) ON DELETE SET NULL,
  CONSTRAINT chk_task_run_attempts_status CHECK (status IN ('pending', 'queued', 'dispatched', 'running', 'canceling', 'success', 'failed', 'timeout', 'canceled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS task_run_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  run_target_id BIGINT UNSIGNED NOT NULL,
  attempt_id BIGINT UNSIGNED NOT NULL,
  sequence BIGINT UNSIGNED NOT NULL,
  stream VARCHAR(16) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  content_hash CHAR(64) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_run_logs_attempt_sequence (attempt_id, sequence),
  KEY idx_task_run_logs_run_sequence (run_id, sequence),
  KEY idx_task_run_logs_target_sequence (run_target_id, sequence),
  KEY idx_task_run_logs_created (created_at),
  CONSTRAINT fk_task_run_logs_run FOREIGN KEY (run_id) REFERENCES task_runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_run_logs_target FOREIGN KEY (run_target_id) REFERENCES task_run_targets(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_run_logs_attempt FOREIGN KEY (attempt_id) REFERENCES task_run_attempts(id) ON DELETE CASCADE,
  CONSTRAINT chk_task_run_logs_stream CHECK (stream IN ('stdout', 'stderr', 'system'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS task_run_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  run_target_id BIGINT UNSIGNED NULL,
  attempt_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(64) NOT NULL,
  from_status VARCHAR(32) NULL,
  to_status VARCHAR(32) NULL,
  message VARCHAR(1024) NULL,
  payload JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_task_run_events_run_created (run_id, created_at),
  KEY idx_task_run_events_target_created (run_target_id, created_at),
  KEY idx_task_run_events_type_created (event_type, created_at),
  CONSTRAINT fk_task_run_events_run FOREIGN KEY (run_id) REFERENCES task_runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_run_events_target FOREIGN KEY (run_target_id) REFERENCES task_run_targets(id) ON DELETE SET NULL,
  CONSTRAINT fk_task_run_events_attempt FOREIGN KEY (attempt_id) REFERENCES task_run_attempts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS task_run_artifacts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  run_id BIGINT UNSIGNED NOT NULL,
  attempt_id BIGINT UNSIGNED NULL,
  name VARCHAR(255) NOT NULL,
  artifact_type VARCHAR(64) NOT NULL,
  storage_url VARCHAR(1024) NOT NULL,
  size_bytes BIGINT UNSIGNED NULL,
  checksum CHAR(64) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_run_artifacts_uid (uid),
  KEY idx_task_run_artifacts_run (run_id),
  KEY idx_task_run_artifacts_attempt (attempt_id),
  CONSTRAINT fk_task_run_artifacts_run FOREIGN KEY (run_id) REFERENCES task_runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_run_artifacts_attempt FOREIGN KEY (attempt_id) REFERENCES task_run_attempts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS schedules (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  task_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  schedule_type VARCHAR(32) NOT NULL,
  cron_expr VARCHAR(128) NULL,
  interval_seconds INT UNSIGNED NULL,
  run_at DATETIME(3) NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  next_fire_at DATETIME(3) NULL,
  last_fire_at DATETIME(3) NULL,
  misfire_policy VARCHAR(32) NOT NULL DEFAULT 'skip',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_schedules_uid (uid),
  UNIQUE KEY uk_schedules_workspace_name (workspace_id, name),
  KEY idx_schedules_workspace_status_next (workspace_id, status, next_fire_at),
  KEY idx_schedules_task (task_id),
  KEY idx_schedules_created_by (created_by),
  CONSTRAINT fk_schedules_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_schedules_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  CONSTRAINT fk_schedules_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_schedules_type CHECK (schedule_type IN ('once', 'interval', 'cron')),
  CONSTRAINT chk_schedules_status CHECK (status IN ('active', 'paused', 'disabled', 'archived')),
  CONSTRAINT chk_schedules_misfire CHECK (misfire_policy IN ('skip', 'fire_once', 'fire_all'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS schedule_triggers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  schedule_id BIGINT UNSIGNED NOT NULL,
  task_run_id BIGINT UNSIGNED NULL,
  planned_fire_at DATETIME(3) NOT NULL,
  actual_fire_at DATETIME(3) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  error_message VARCHAR(1024) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_schedule_triggers_schedule_planned (schedule_id, planned_fire_at),
  KEY idx_schedule_triggers_status_planned (status, planned_fire_at),
  KEY idx_schedule_triggers_run (task_run_id),
  CONSTRAINT fk_schedule_triggers_schedule FOREIGN KEY (schedule_id) REFERENCES schedules(id) ON DELETE CASCADE,
  CONSTRAINT fk_schedule_triggers_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE SET NULL,
  CONSTRAINT chk_schedule_triggers_status CHECK (status IN ('pending', 'fired', 'skipped', 'failed', 'canceled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS metric_definitions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(128) NOT NULL,
  name VARCHAR(128) NOT NULL,
  unit VARCHAR(32) NULL,
  description VARCHAR(512) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_metric_definitions_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS host_metrics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL,
  host_id BIGINT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NULL,
  metric_code VARCHAR(128) NOT NULL,
  metric_value DECIMAL(20, 6) NOT NULL,
  unit VARCHAR(32) NULL,
  dimensions JSON NULL,
  collected_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_host_metrics_host_metric_time (host_id, metric_code, collected_at),
  KEY idx_host_metrics_workspace_time (workspace_id, collected_at),
  KEY idx_host_metrics_agent_time (agent_id, collected_at),
  CONSTRAINT fk_host_metrics_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_host_metrics_host FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE CASCADE,
  CONSTRAINT fk_host_metrics_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS service_checks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  host_id BIGINT UNSIGNED NULL,
  name VARCHAR(128) NOT NULL,
  check_type VARCHAR(32) NOT NULL,
  target VARCHAR(1024) NOT NULL,
  interval_seconds INT UNSIGNED NOT NULL DEFAULT 60,
  timeout_seconds INT UNSIGNED NOT NULL DEFAULT 5,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  config JSON NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_service_checks_uid (uid),
  KEY idx_service_checks_workspace_status (workspace_id, status),
  KEY idx_service_checks_host (host_id),
  KEY idx_service_checks_created_by (created_by),
  CONSTRAINT fk_service_checks_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_service_checks_host FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE SET NULL,
  CONSTRAINT fk_service_checks_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_service_checks_type CHECK (check_type IN ('http', 'tcp', 'process', 'script')),
  CONSTRAINT chk_service_checks_status CHECK (status IN ('active', 'paused', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS service_check_results (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  service_check_id BIGINT UNSIGNED NOT NULL,
  host_id BIGINT UNSIGNED NULL,
  status VARCHAR(32) NOT NULL,
  latency_ms INT UNSIGNED NULL,
  output VARCHAR(2048) NULL,
  checked_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_service_check_results_check_time (service_check_id, checked_at),
  KEY idx_service_check_results_host_time (host_id, checked_at),
  KEY idx_service_check_results_status_time (status, checked_at),
  CONSTRAINT fk_service_check_results_check FOREIGN KEY (service_check_id) REFERENCES service_checks(id) ON DELETE CASCADE,
  CONSTRAINT fk_service_check_results_host FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE SET NULL,
  CONSTRAINT chk_service_check_results_status CHECK (status IN ('up', 'down', 'degraded', 'unknown'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS alert_rules (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  rule_type VARCHAR(32) NOT NULL,
  metric_code VARCHAR(128) NULL,
  operator VARCHAR(16) NULL,
  threshold DECIMAL(20, 6) NULL,
  duration_seconds INT UNSIGNED NOT NULL DEFAULT 60,
  severity VARCHAR(32) NOT NULL DEFAULT 'warning',
  expression JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_alert_rules_uid (uid),
  UNIQUE KEY uk_alert_rules_workspace_name (workspace_id, name),
  KEY idx_alert_rules_workspace_status (workspace_id, status),
  KEY idx_alert_rules_metric (metric_code),
  KEY idx_alert_rules_created_by (created_by),
  CONSTRAINT fk_alert_rules_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_alert_rules_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_alert_rules_type CHECK (rule_type IN ('metric', 'agent_offline', 'service_check', 'task_failed', 'custom')),
  CONSTRAINT chk_alert_rules_severity CHECK (severity IN ('info', 'warning', 'critical')),
  CONSTRAINT chk_alert_rules_status CHECK (status IN ('active', 'paused', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  alert_rule_id BIGINT UNSIGNED NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id BIGINT UNSIGNED NULL,
  title VARCHAR(255) NOT NULL,
  message VARCHAR(2048) NULL,
  severity VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'firing',
  fingerprint CHAR(64) NOT NULL,
  open_fingerprint CHAR(64) GENERATED ALWAYS AS (
    CASE
      WHEN status IN ('firing', 'acknowledged', 'silenced') THEN fingerprint
      ELSE NULL
    END
  ) STORED,
  first_seen_at DATETIME(3) NOT NULL,
  last_seen_at DATETIME(3) NOT NULL,
  resolved_at DATETIME(3) NULL,
  resolved_by BIGINT UNSIGNED NULL,
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_alerts_uid (uid),
  UNIQUE KEY uk_alerts_open_fingerprint (workspace_id, open_fingerprint),
  KEY idx_alerts_workspace_status_severity (workspace_id, status, severity),
  KEY idx_alerts_rule (alert_rule_id),
  KEY idx_alerts_resource (workspace_id, resource_type, resource_id),
  KEY idx_alerts_resolved_by (resolved_by),
  CONSTRAINT fk_alerts_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_alerts_rule FOREIGN KEY (alert_rule_id) REFERENCES alert_rules(id) ON DELETE SET NULL,
  CONSTRAINT fk_alerts_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_alerts_severity CHECK (severity IN ('info', 'warning', 'critical')),
  CONSTRAINT chk_alerts_status CHECK (status IN ('firing', 'acknowledged', 'resolved', 'silenced'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS alert_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  alert_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  message VARCHAR(1024) NULL,
  actor_id BIGINT UNSIGNED NULL,
  payload JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_alert_events_alert_created (alert_id, created_at),
  KEY idx_alert_events_actor (actor_id),
  CONSTRAINT fk_alert_events_alert FOREIGN KEY (alert_id) REFERENCES alerts(id) ON DELETE CASCADE,
  CONSTRAINT fk_alert_events_actor FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS notification_channels (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  channel_type VARCHAR(32) NOT NULL,
  config JSON NULL,
  secret_ref VARCHAR(255) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_notification_channels_uid (uid),
  UNIQUE KEY uk_notification_channels_workspace_name (workspace_id, name),
  KEY idx_notification_channels_workspace_status (workspace_id, status),
  KEY idx_notification_channels_created_by (created_by),
  CONSTRAINT fk_notification_channels_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_notification_channels_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_notification_channels_type CHECK (channel_type IN ('site', 'email', 'webhook', 'dingtalk', 'wechat', 'slack')),
  CONSTRAINT chk_notification_channels_status CHECK (status IN ('active', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  recipient_user_id BIGINT UNSIGNED NULL,
  title VARCHAR(255) NOT NULL,
  content VARCHAR(2048) NULL,
  category VARCHAR(64) NOT NULL,
  severity VARCHAR(32) NOT NULL DEFAULT 'info',
  resource_type VARCHAR(64) NULL,
  resource_id BIGINT UNSIGNED NULL,
  read_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_notifications_uid (uid),
  KEY idx_notifications_workspace_created (workspace_id, created_at),
  KEY idx_notifications_recipient_read (recipient_user_id, read_at, created_at),
  CONSTRAINT fk_notifications_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT chk_notifications_severity CHECK (severity IN ('info', 'warning', 'critical'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS notification_deliveries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  notification_id BIGINT UNSIGNED NOT NULL,
  channel_id BIGINT UNSIGNED NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  next_retry_at DATETIME(3) NULL,
  delivered_at DATETIME(3) NULL,
  error_message VARCHAR(1024) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_notification_deliveries_status_retry (status, next_retry_at),
  KEY idx_notification_deliveries_notification (notification_id),
  KEY idx_notification_deliveries_channel (channel_id),
  CONSTRAINT fk_notification_deliveries_notification FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE,
  CONSTRAINT fk_notification_deliveries_channel FOREIGN KEY (channel_id) REFERENCES notification_channels(id) ON DELETE SET NULL,
  CONSTRAINT chk_notification_deliveries_status CHECK (status IN ('pending', 'sending', 'success', 'failed', 'canceled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS webhook_sources (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'custom',
  token_hash CHAR(64) NOT NULL,
  secret_hash CHAR(64) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  last_received_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_webhook_sources_uid (uid),
  UNIQUE KEY uk_webhook_sources_token (token_hash),
  UNIQUE KEY uk_webhook_sources_workspace_name (workspace_id, name),
  KEY idx_webhook_sources_workspace_status (workspace_id, status),
  KEY idx_webhook_sources_created_by (created_by),
  CONSTRAINT fk_webhook_sources_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_webhook_sources_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_webhook_sources_type CHECK (source_type IN ('github', 'gitee', 'gitlab', 'custom')),
  CONSTRAINT chk_webhook_sources_status CHECK (status IN ('active', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS webhook_rules (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  source_id BIGINT UNSIGNED NOT NULL,
  task_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  event_type VARCHAR(128) NULL,
  matcher JSON NULL,
  parameter_mapping JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_webhook_rules_uid (uid),
  UNIQUE KEY uk_webhook_rules_source_name (source_id, name),
  KEY idx_webhook_rules_workspace_status (workspace_id, status),
  KEY idx_webhook_rules_task (task_id),
  KEY idx_webhook_rules_created_by (created_by),
  CONSTRAINT fk_webhook_rules_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_webhook_rules_source FOREIGN KEY (source_id) REFERENCES webhook_sources(id) ON DELETE CASCADE,
  CONSTRAINT fk_webhook_rules_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE RESTRICT,
  CONSTRAINT fk_webhook_rules_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_webhook_rules_status CHECK (status IN ('active', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS webhook_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  source_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(128) NULL,
  delivery_id VARCHAR(191) NULL,
  signature_valid TINYINT(1) NOT NULL DEFAULT 0,
  replayed TINYINT(1) NOT NULL DEFAULT 0,
  remote_ip VARCHAR(45) NULL,
  headers JSON NULL,
  payload JSON NULL,
  payload_hash CHAR(64) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'received',
  error_message VARCHAR(1024) NULL,
  received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_webhook_events_uid (uid),
  UNIQUE KEY uk_webhook_events_delivery (source_id, delivery_id),
  KEY idx_webhook_events_workspace_received (workspace_id, received_at),
  KEY idx_webhook_events_source_received (source_id, received_at),
  KEY idx_webhook_events_status_received (status, received_at),
  CONSTRAINT fk_webhook_events_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_webhook_events_source FOREIGN KEY (source_id) REFERENCES webhook_sources(id) ON DELETE SET NULL,
  CONSTRAINT chk_webhook_events_status CHECK (status IN ('received', 'matched', 'ignored', 'triggered', 'failed', 'rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS webhook_event_matches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_id BIGINT UNSIGNED NOT NULL,
  rule_id BIGINT UNSIGNED NULL,
  task_run_id BIGINT UNSIGNED NULL,
  matched TINYINT(1) NOT NULL DEFAULT 0,
  reason VARCHAR(1024) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_webhook_event_matches_event (event_id),
  KEY idx_webhook_event_matches_rule (rule_id),
  KEY idx_webhook_event_matches_run (task_run_id),
  CONSTRAINT fk_webhook_event_matches_event FOREIGN KEY (event_id) REFERENCES webhook_events(id) ON DELETE CASCADE,
  CONSTRAINT fk_webhook_event_matches_rule FOREIGN KEY (rule_id) REFERENCES webhook_rules(id) ON DELETE SET NULL,
  CONSTRAINT fk_webhook_event_matches_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NULL,
  actor_type VARCHAR(32) NOT NULL DEFAULT 'user',
  actor_user_id BIGINT UNSIGNED NULL,
  actor_agent_id BIGINT UNSIGNED NULL,
  action VARCHAR(128) NOT NULL,
  resource_type VARCHAR(64) NULL,
  resource_id BIGINT UNSIGNED NULL,
  result VARCHAR(32) NOT NULL DEFAULT 'success',
  ip VARCHAR(45) NULL,
  user_agent VARCHAR(512) NULL,
  trace_id VARCHAR(64) NULL,
  request_method VARCHAR(16) NULL,
  request_path VARCHAR(512) NULL,
  before_data JSON NULL,
  after_data JSON NULL,
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_audit_logs_workspace_created (workspace_id, created_at),
  KEY idx_audit_logs_actor_user_created (actor_user_id, created_at),
  KEY idx_audit_logs_actor_agent_created (actor_agent_id, created_at),
  KEY idx_audit_logs_resource_created (workspace_id, resource_type, resource_id, created_at),
  KEY idx_audit_logs_action_created (action, created_at),
  KEY idx_audit_logs_trace (trace_id),
  CONSTRAINT fk_audit_logs_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE SET NULL,
  CONSTRAINT fk_audit_logs_actor_user FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_audit_logs_actor_agent FOREIGN KEY (actor_agent_id) REFERENCES agents(id) ON DELETE SET NULL,
  CONSTRAINT chk_audit_logs_actor CHECK (actor_type IN ('user', 'agent', 'webhook', 'system')),
  CONSTRAINT chk_audit_logs_result CHECK (result IN ('success', 'failed', 'denied'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS idempotency_keys (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL,
  key_hash CHAR(64) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id BIGINT UNSIGNED NULL,
  request_hash CHAR(64) NULL,
  response_snapshot JSON NULL,
  expires_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_idempotency_keys_hash (workspace_id, key_hash),
  KEY idx_idempotency_keys_expires (expires_at),
  CONSTRAINT fk_idempotency_keys_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS outbox_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NULL,
  aggregate_type VARCHAR(64) NOT NULL,
  aggregate_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  payload JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  next_retry_at DATETIME(3) NULL,
  published_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_outbox_events_uid (uid),
  KEY idx_outbox_events_status_retry (status, next_retry_at, created_at),
  KEY idx_outbox_events_aggregate (aggregate_type, aggregate_id),
  CONSTRAINT fk_outbox_events_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE SET NULL,
  CONSTRAINT chk_outbox_events_status CHECK (status IN ('pending', 'publishing', 'published', 'failed', 'canceled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;
