CREATE TABLE IF NOT EXISTS agent_diagnostics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NOT NULL,
  host_id BIGINT UNSIGNED NULL,
  version VARCHAR(64) NULL,
  os_name VARCHAR(128) NULL,
  os_version VARCHAR(128) NULL,
  arch VARCHAR(64) NULL,
  ip VARCHAR(45) NULL,
  running_tasks INT UNSIGNED NULL,
  payload JSON NULL,
  reported_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_diagnostics_uid (uid),
  KEY idx_agent_diagnostics_workspace_reported (workspace_id, reported_at),
  KEY idx_agent_diagnostics_agent_reported (agent_id, reported_at),
  CONSTRAINT fk_agent_diagnostics_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_diagnostics_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_diagnostics_host FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS maintenance_windows (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  scope_type VARCHAR(32) NOT NULL DEFAULT 'all',
  agent_id BIGINT UNSIGNED NULL,
  host_id BIGINT UNSIGNED NULL,
  reason VARCHAR(512) NULL,
  starts_at DATETIME(3) NOT NULL,
  ends_at DATETIME(3) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_maintenance_windows_uid (uid),
  UNIQUE KEY uk_maintenance_windows_workspace_name (workspace_id, name),
  KEY idx_maintenance_windows_scope (workspace_id, status, scope_type, starts_at, ends_at),
  KEY idx_maintenance_windows_agent (agent_id),
  KEY idx_maintenance_windows_host (host_id),
  CONSTRAINT fk_maintenance_windows_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_maintenance_windows_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE SET NULL,
  CONSTRAINT fk_maintenance_windows_host FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE SET NULL,
  CONSTRAINT fk_maintenance_windows_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_maintenance_windows_scope CHECK (scope_type IN ('all', 'agent', 'host')),
  CONSTRAINT chk_maintenance_windows_status CHECK (status IN ('active', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;
