CREATE TABLE IF NOT EXISTS alert_suppression_rules (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  alert_rule_uid CHAR(26) NULL,
  host_uid CHAR(26) NULL,
  severity VARCHAR(32) NULL,
  starts_at DATETIME(3) NULL,
  ends_at DATETIME(3) NULL,
  reason VARCHAR(512) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_alert_suppression_rules_uid (uid),
  UNIQUE KEY uk_alert_suppression_rules_workspace_name (workspace_id, name),
  KEY idx_alert_suppression_rules_match (workspace_id, status, alert_rule_uid, host_uid, severity),
  CONSTRAINT fk_alert_suppression_rules_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_alert_suppression_rules_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_alert_suppression_rules_severity CHECK (severity IS NULL OR severity IN ('info', 'warning', 'critical')),
  CONSTRAINT chk_alert_suppression_rules_status CHECK (status IN ('active', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS alert_routing_policies (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(26) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  alert_rule_uid CHAR(26) NULL,
  host_uid CHAR(26) NULL,
  severity VARCHAR(32) NULL,
  channel_uid CHAR(26) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_alert_routing_policies_uid (uid),
  UNIQUE KEY uk_alert_routing_policies_workspace_name (workspace_id, name),
  KEY idx_alert_routing_policies_match (workspace_id, status, alert_rule_uid, host_uid, severity),
  CONSTRAINT fk_alert_routing_policies_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_alert_routing_policies_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_alert_routing_policies_severity CHECK (severity IS NULL OR severity IN ('info', 'warning', 'critical')),
  CONSTRAINT chk_alert_routing_policies_status CHECK (status IN ('active', 'disabled', 'archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;
